import BigNumber from 'bignumber.js';

// URLS
export const GAS_PRICE_API = 'https://gasprice.poa.network/';
export const ZAPPER_GAS_PRICE_API = 'https://api.zapper.fi/v1/gas-price?api_key=96e0cc51-a62e-42ca-acee-910ea7d2a241'
export const ETHERSCAN_URL = 'https://etherscan.io/';


// DEFINE CONTRACT ADDRESSES
export const Y_DELEGATE_ADDRESS = '0xd4Aa6370DeB717eF707f9F62677B90b5Df4349D0'
export const AAVE_LENDING_POOL_ADDRESS = '0x7d2768de32b0b80b7a3454c06bdac94a69ddc7a9'
export const AAVE_ORACLE_ADDRESS = '0xa50ba011c48153de246e5192c8f9258a2ba79ca9'

// GENERAL
export const ERROR = 'ERROR';
export const STORE_UPDATED = 'STORE_UPDATED';
export const TX_SUBMITTED = 'TX_SUBMITTED';

export const CONNECTION_CONNECTED = 'CONNECTION_CONNECTED';
export const CONNECTION_DISCONNECTED = 'CONNECTION_DISCONNECTED';
export const CONNECT_WALLET = 'CONNECT_WALLET';

export const CONFIGURE = 'CONFIGURE';
export const CONFIGURE_RETURNED = 'CONFIGURE_RETURNED';

export const ACCOUNT_CONFIGURED = 'ACCOUNT_CONFIGURED';
export const ACCOUNT_CHANGED = 'ACCOUNT_CHANGED';

export const GET_GAS_PRICES = 'GET_GAS_PRICES';
export const GAS_PRICES_RETURNED = 'GAS_PRICES_RETURNED';


// DELEGATE
export const CONFIGURE_DELEGATE = 'CONFIGURE_DELEGATE'
export const DELEGATE_CONFIGURED = 'DELEGATE_CONFIGURED'

export const GET_ASSETS = 'GET_ASSETS'
export const ASSETS_RETURNED = 'ASSETS_RETURNED'

export const DELEGATE_GET_BALANCES = 'DELEGATE_GET_BALANCES'
export const DELEGATE_BALANCES_RETURNED = 'DELEGATE_BALANCES_RETURNED'

export const DELEGATE_APPROVE_DEPOSIT = 'DELEGATE_APPROVE_DEPOSIT'
export const DELEGATE_APPROVE_DEPOSIT_RETURNED = 'DELEGATE_APPROVE_DEPOSIT_RETURNED'

export const DELEGATE_DEPOSIT = 'DELEGATE_DEPOSIT'
export const DELEGATE_DEPOSIT_RETURNED = 'DELEGATE_DEPOSIT_RETURNED'

export const DELEGATE_APPROVE_WITHDRAW = 'DELEGATE_APPROVE_WITHDRAW'
export const DELEGATE_APPROVE_WITHDRAW_RETURNED = 'DELEGATE_APPROVE_WITHDRAW_RETURNED'

export const DELEGATE_WITHDRAW = 'DELEGATE_WITHDRAW'
export const DELEGATE_WITHDRAW_RETURNED = 'DELEGATE_WITHDRAW_RETURNED'


export const MAX_UINT256 = new BigNumber(2).pow(256).minus(1).toFixed(0);
